{{- if .Values.kubernetesManager.enableLeaderElection }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cluster-monitor-agent.fullname" . }}
  labels:
    {{- include "cluster-monitor-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
{{- end -}}
